### ISSUE TITLE
在红米手机1代下打开失败，无法安装。

### ISSUE THREAD

**Issue by ruleroller** [lparam/xsocks-android#1]
提示：解析错误，解析包时出现问题。

xsocks-android：最新版的1.2.0
Android version：4.2.1 hm2013022
MIUI：miui-jhachbf 17.0

**Comment by lparam** [comment]
重新下载apk或试试v1.1.7，排除一下是否包损坏

**Comment by ruleroller** [comment]
刚才下载了1.1.7，它的md5是不是 177aae4cdf0431f708911a203bef82a1
也是一样的安装不了，点击安装就提示解析包时出现问题。

**Comment by lparam** [comment]
1.2.0的md5是63234f4770fa480a3b33476ed49a2be4，你检查一下。如果是正确的，那估计是小米ROM方面的问题。如果有条件，建议你在别的ROM上面试试。

**Comment by ruleroller** [comment]
我下载1.2.0版本，用的这个链接
https://github.com/lparam/xsocks-android/releases/download/v1.2.0/Xsocks-v1.2.0.apk ，
得到的md5 是18e00a08520cc87bae51c90415b12397 ，和你的不同哦，并且也还是装不了的，怎么会这样呢？

对了，1.1.7md5，和我说一样的吗？

我也没有其它Android手机，实在装不了就算了，多半是MIUI的问题。

**Comment by lparam** [comment]
我手上现在没有1.1.7的apk。你能否发封空邮件给我，我把我机器上的文件发送到你邮件试试。

**Comment by cokebar** [comment]
@lparam 1.2.0的release有问题  apk不到2M 而1.1.7的包有4MB多 差得太大了
同样求发送：cokebar@cokebar.info

**Comment by lparam** [comment]
@cokebar 1.2.0之所以比1.1.7小这么多，是因为移除了realm这个包，用GSON代替了。
你是手机什么型号，是什么ROM, 什么版本?

**Comment by cokebar** [comment]
@lparam 华为荣耀7 EMUI3.1 Android 5.0.2
打开时候界面闪一下没了

**Comment by cokebar** [comment]
今天晚上回去再拿nexus 7 试试

**Comment by lparam** [comment]
@cokebar 据反馈，在荣耀6+, 4.4.2 上使用没问题。
我自己使用Nexus4, 在Nexus5上也测试过。

**Comment by cokebar** [comment]
@lparam 能否发一份您机子上的1.2.0版本 我这里md5跟 @ruleroller 的一样

**Comment by lparam** [comment]
@cokebar 已发，如果还是无法安装，有条件的话请自行下载源码debug，并提交pr。

**Comment by lparam** [comment]
@ruleroller @cokebar 试试1.2.1? 在酷派上都测试过没问题。

**Comment by ruleroller** [comment]
1.2.1 的md5 是不是 9b702bf099847b1ecb897017bb1baa28 ？
依旧无法安装。 ___
![screenshot_2015-09-12-22-52-05](https://cloud.githubusercontent.com/assets/3047708/9832047/46e08422-59a1-11e5-9309-541ff20c4445.png)

**Comment by lparam** [comment]
＠ruleroller md5是对的，要不你在android studio上试试？

**Comment by ruleroller** [comment]
@lparam 不懂android studio是什么，我只是一个普通用户，不是程序员啊。

**Comment by lparam** [comment]
@ruleroller 那这个问题等我手上有红米1再说吧
