### ISSUE TITLE
Is xsocks-android compatible with Android 5.0+?

### ISSUE THREAD

**Issue by cokebar** [lparam/xsocks-android#2]
v1.2.0 release apk file is not good. It can install on my phone but cannot run.
v1.1.7 can run, but can't start the service. When I turned the switch on, it crashed.
Huawei Honor 7, Emotion UI 3.1, Android 5.0.2, no root.
1.1.7 need root?

**Comment by lparam** [comment]
1. Don't need to root. 
2. It's compatible with 5.0.
3. Refer issue #1
