### ISSUE TITLE
Unable to Make project

### ISSUE THREAD

**Issue by aalgingi** [lparam/xsocks-android#3]
Hello,

i tried to make the JNI libs as instructed in the read me file but its complaining some files do not exist. Below is the console output. Any idea if i am missing anything?

install: jni/xSocks/xSocks-android-i686/xSocks: No such file or directory
install: jni/xSocks/xSocks-android-i686/xForwarder: No such file or directory
install: jni/xSocks/xSocks-android-armv7-a/xSocks: No such file or directory
install: jni/xSocks/xSocks-android-armv7-a/xForwarder: No such file or directory

make
if [ a == a/Users/algingihy/Library/Android/android-ndk-r10e ]; then \
        echo ANDROID_NDK_HOME is not set ;\
        exit 1 ;\
    fi ;\
    pushd jni/xSocks || exit 1 ;\
    dist-build/android-x86.sh || exit 1 ;\
    dist-build/android-armv7-a.sh || exit 1 ;\
    popd ;\
    pushd jni ;\
    /Users/algingihy/Library/Android/android-ndk-r10e/ndk-build NDK_LOG=1 V=0 || exit 1 ;\
    popd ;\
    rm -rf app/src/main/assets/x86 ;\
    rm -rf app/src/main/assets/armeabi-v7a ;\
    mkdir -p app/src/main/assets/x86 ;\
    mkdir -p app/src/main/assets/armeabi-v7a ;\
    install -d app/src/main/jniLibs/x86 ;\
    install -d app/src/main/jniLibs/armeabi-v7a ;\
    install libs/x86/pdnsd app/src/main/assets/x86 ;\
    install libs/x86/tun2socks app/src/main/assets/x86 ;\
    install libs/x86/libsystem.so app/src/main/jniLibs/x86 ;\
    install libs/armeabi-v7a/pdnsd app/src/main/assets/armeabi-v7a ;\
    install libs/armeabi-v7a/tun2socks app/src/main/assets/armeabi-v7a ;\
    install libs/armeabi-v7a/libsystem.so app/src/main/jniLibs/armeabi-v7a ;\
    install jni/xSocks/xSocks-android-i686/xSocks app/src/main/assets/x86 ;\
    install jni/xSocks/xSocks-android-i686/xForwarder app/src/main/assets/x86 ;\
    install jni/xSocks/xSocks-android-armv7-a/xSocks app/src/main/assets/armeabi-v7a ;\
    install jni/xSocks/xSocks-android-armv7-a/xForwarder app/src/main/assets/armeabi-v7a ;
~/xSocks-android/jni/xSocks ~/xSocks-android
- glibtoolize
- aclocal -I m4
- autoconf
- automake --add-missing --copy
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for i686-linux-android-strip... i686-linux-android-strip
  checking for a thread-safe mkdir -p... /Users/algingihy/xSocks-android/jni/xSocks/3rd/libuv/install-sh -c -d
  checking for gawk... no
  checking for mawk... no
  checking for nawk... no
  checking for awk... awk
  checking whether /Applications/Xcode.app/Contents/Developer/usr/bin/make sets $(MAKE)... yes
  checking whether /Applications/Xcode.app/Contents/Developer/usr/bin/make supports nested variables... yes
  configure: error: source directory already configured; run "make distclean" there first
  make[1]: **\* [/Users/algingihy/xSocks-android/jni/xSocks/xSocks-android-i686/3rd/libuv/Makefile] Error 1
  i686-linux-android-strip: '/Users/algingihy/xSocks-android/jni/xSocks/xSocks-android-i686/xSocks': No such file
  i686-linux-android-strip: '/Users/algingihy/xSocks-android/jni/xSocks/xSocks-android-i686/xForwarder': No such file
  xSocks has been installed into /Users/algingihy/xSocks-android/jni/xSocks/xSocks-android-i686
- glibtoolize
- aclocal -I m4
- autoconf
- automake --add-missing --copy
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for arm-linux-androideabi-strip... arm-linux-androideabi-strip
  checking for a thread-safe mkdir -p... /Users/algingihy/xSocks-android/jni/xSocks/3rd/libuv/install-sh -c -d
  checking for gawk... no
  checking for mawk... no
  checking for nawk... no
  checking for awk... awk
  checking whether /Applications/Xcode.app/Contents/Developer/usr/bin/make sets $(MAKE)... yes
  checking whether /Applications/Xcode.app/Contents/Developer/usr/bin/make supports nested variables... yes
  configure: error: source directory already configured; run "make distclean" there first
  make[1]: **\* [/Users/algingihy/xSocks-android/jni/xSocks/xSocks-android-armv7-a/3rd/libuv/Makefile] Error 1
  arm-linux-androideabi-strip: '/Users/algingihy/xSocks-android/jni/xSocks/xSocks-android-armv7-a/xSocks': No such file
  arm-linux-androideabi-strip: '/Users/algingihy/xSocks-android/jni/xSocks/xSocks-android-armv7-a/xForwarder': No such file
  xSocks has been installed into /Users/algingihy/xSocks-android/jni/xSocks/xSocks-android-armv7-a
  ~/xSocks-android
  ~/xSocks-android/jni ~/xSocks-android
  HOST_OS=darwin
  HOST_ARCH=x86_64
  HOST_TAG=darwin-x86_64 
  GNUMAKE=/Users/algingihy/Library/Android/android-ndk-r10e/prebuilt/darwin-x86_64/bin/make (NDK prebuilt)
  Android NDK: NDK installation path auto-detected: '/Users/algingihy/Library/Android/android-ndk-r10e'
  Android NDK: GNU Make version 3.81 detected
  Android NDK: Host OS was auto-detected: darwin
  Android NDK:  Host operating system detected: darwin
  Android NDK: Host CPU was auto-detected: x86
  Android NDK: HOST_TAG set to darwin-x86
  Android NDK: Host tools prebuilt directory: /Users/algingihy/Library/Android/android-ndk-r10e/prebuilt/darwin-x86_64/bin
  Android NDK: Host 'echo' tool: echo
  Android NDK: Host 'echo -n' tool: printf %s
  Android NDK: Host 'cmp' tool: cmp
  Android NDK: Host 'awk' tool: /Users/algingihy/Library/Android/android-ndk-r10e/prebuilt/darwin-x86_64/bin/awk
  Android NDK: Host 'awk' test returned: Pass
  Android NDK: Found platform root directory: /Users/algingihy/Library/Android/android-ndk-r10e/platforms
  Android NDK: Found supported platforms: android-12 android-13 android-14 android-15 android-16 android-17 android-18 android-19 android-21 android-3 android-4 android-5 android-8 android-9
  Android NDK: PLATFORM android-12 supports: arm mips x86
  Android NDK:   ABI arm sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-12/arch-arm
  Android NDK:   ABI mips sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-12/arch-mips
  Android NDK:   ABI x86 sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-12/arch-x86
  Android NDK: PLATFORM android-13 supports: arm mips x86
  Android NDK:   ABI arm sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-13/arch-arm
  Android NDK:   ABI mips sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-13/arch-mips
  Android NDK:   ABI x86 sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-13/arch-x86
  Android NDK: PLATFORM android-14 supports: arm mips x86
  Android NDK:   ABI arm sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-14/arch-arm
  Android NDK:   ABI mips sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-14/arch-mips
  Android NDK:   ABI x86 sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-14/arch-x86
  Android NDK: PLATFORM android-15 supports: arm mips x86
  Android NDK:   ABI arm sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-15/arch-arm
  Android NDK:   ABI mips sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-15/arch-mips
  Android NDK:   ABI x86 sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-15/arch-x86
  Android NDK: PLATFORM android-16 supports: arm mips x86
  Android NDK:   ABI arm sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-16/arch-arm
  Android NDK:   ABI mips sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-16/arch-mips
  Android NDK:   ABI x86 sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-16/arch-x86
  Android NDK: PLATFORM android-17 supports: arm mips x86
  Android NDK:   ABI arm sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-17/arch-arm
  Android NDK:   ABI mips sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-17/arch-mips
  Android NDK:   ABI x86 sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-17/arch-x86
  Android NDK: PLATFORM android-18 supports: arm mips x86
  Android NDK:   ABI arm sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-18/arch-arm
  Android NDK:   ABI mips sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-18/arch-mips
  Android NDK:   ABI x86 sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-18/arch-x86
  Android NDK: PLATFORM android-19 supports: arm mips x86
  Android NDK:   ABI arm sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-19/arch-arm
  Android NDK:   ABI mips sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-19/arch-mips
  Android NDK:   ABI x86 sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-19/arch-x86
  Android NDK: PLATFORM android-21 supports: arm arm64 mips mips64 x86 x86_64
  Android NDK:   ABI arm sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-21/arch-arm
  Android NDK:   ABI arm64 sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-21/arch-arm64
  Android NDK:   ABI mips sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-21/arch-mips
  Android NDK:   ABI mips64 sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-21/arch-mips64
  Android NDK:   ABI x86 sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-21/arch-x86
  Android NDK:   ABI x86_64 sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-21/arch-x86_64
  Android NDK: PLATFORM android-3 supports: arm
  Android NDK:   ABI arm sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-3/arch-arm
  Android NDK: PLATFORM android-4 supports: arm
  Android NDK:   ABI arm sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-4/arch-arm
  Android NDK: PLATFORM android-5 supports: arm
  Android NDK:   ABI arm sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-5/arch-arm
  Android NDK: PLATFORM android-8 supports: arm
  Android NDK:   ABI arm sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-8/arch-arm
  Android NDK: PLATFORM android-9 supports: arm mips x86
  Android NDK:   ABI arm sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-9/arch-arm
  Android NDK:   ABI mips sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-9/arch-mips
  Android NDK:   ABI x86 sysroot is: /Users/algingihy/Library/Android/android-ndk-r10e/platforms/android-9/arch-x86
  Android NDK: Found stable platform levels: 12 13 14 15 16 17 18 19 21 3 4 5 8 9
  Android NDK: Found max platform level: 21
  Android NDK:  This NDK supports the following target architectures and ABIS:
  Android NDK:    arm: armeabi armeabi-v7a armeabi-v7a-hard
  Android NDK:    arm64: arm64-v8a
  Android NDK:    mips: mips
  Android NDK:    mips64: mips64
  Android NDK:    x86: x86
  Android NDK:    x86_64: x86_64
  Android NDK:  This NDK supports the following toolchains and target ABIs:
  Android NDK:    aarch64-linux-android-4.9:  arm64-v8a
  Android NDK:    aarch64-linux-android-clang3.5:  arm64-v8a
  Android NDK:    aarch64-linux-android-clang3.6:  arm64-v8a
  Android NDK:    arm-linux-androideabi-4.8:  armeabi armeabi-v7a armeabi-v7a-hard
  Android NDK:    arm-linux-androideabi-4.9:  armeabi armeabi-v7a armeabi-v7a-hard
  Android NDK:    arm-linux-androideabi-clang3.5:  armeabi armeabi-v7a armeabi-v7a-hard
  Android NDK:    arm-linux-androideabi-clang3.6:  armeabi armeabi-v7a armeabi-v7a-hard
  Android NDK:    mips64el-linux-android-4.9:  mips64
  Android NDK:    mips64el-linux-android-clang3.5:  mips64
  Android NDK:    mips64el-linux-android-clang3.6:  mips64
  Android NDK:    mipsel-linux-android-4.8:  mips
  Android NDK:    mipsel-linux-android-4.9:  mips
  Android NDK:    mipsel-linux-android-clang3.5:  mips
  Android NDK:    mipsel-linux-android-clang3.6:  mips
  Android NDK:    x86-4.8:  x86
  Android NDK:    x86-4.9:  x86
  Android NDK:    x86-clang3.5:  x86
  Android NDK:    x86-clang3.6:  x86
  Android NDK:    x86_64-4.9:  x86_64
  Android NDK:    x86_64-clang3.5:  x86_64
  Android NDK:    x86_64-clang3.6:  x86_64
  Android NDK: Looking for jni/Android.mk in /Users/algingihy/xSocks-android/jni
  Android NDK: Looking for jni/Android.mk in /Users/algingihy/xSocks-android
  Android NDK:     Found it !
  Android NDK: Found project path: /Users/algingihy/xSocks-android
  Android NDK: Ouput path for intermediate files: /Users/algingihy/xSocks-android/obj
  Android NDK: Ouput path for generated library files: /Users/algingihy/xSocks-android/libs
  Android NDK: Parsing /Users/algingihy/xSocks-android/jni/Application.mk
  Android NDK:   APP_PIE is 
  Android NDK:   Enabling -fPIE
  Android NDK:   Defaulted to APP_BUILD_SCRIPT=/Users/algingihy/xSocks-android/jni/Android.mk
  Android NDK: Application 'local' is not debuggable
  Android NDK: Selecting release optimization mode (app is not debuggable)
  Android NDK: Adding import directory: /Users/algingihy/Library/Android/android-ndk-r10e/sources
  Android NDK: Building application 'local' for ABI 'x86'
  Android NDK:   Enabling -fPIE for TARGET_PLATFORM android-16
  Android NDK: Using target toolchain 'x86-4.9' for 'x86' ABI (through NDK_TOOLCHAIN_VERSION)
  Android NDK: Looking for imported module with tag 'cxx-stl/stlport'
  Android NDK:   Probing /Users/algingihy/Library/Android/android-ndk-r10e/sources/cxx-stl/stlport/Android.mk
  Android NDK:     Found in /Users/algingihy/Library/Android/android-ndk-r10e/sources/cxx-stl/stlport
  Android NDK: Using prebuilt STLport libraries
  Android NDK: Looking for imported module with tag 'android/cpufeatures'
  Android NDK:   Probing /Users/algingihy/Library/Android/android-ndk-r10e/sources/android/cpufeatures/Android.mk
  Android NDK:     Found in /Users/algingihy/Library/Android/android-ndk-r10e/sources/android/cpufeatures
  Android NDK: Module 'system' has C++ sources
  Android NDK: Add dependency 'stlport_static' to module 'system'
  Android NDK: [x86] Modules to build: pdnsd system tun2socks
  Android NDK: Building application 'local' for ABI 'armeabi-v7a'
  Android NDK:   Enabling -fPIE for TARGET_PLATFORM android-16
  Android NDK: Using target toolchain 'arm-linux-androideabi-4.9' for 'armeabi-v7a' ABI (through NDK_TOOLCHAIN_VERSION)
  Android NDK: Looking for imported module with tag 'cxx-stl/stlport'
  Android NDK:   Probing /Users/algingihy/Library/Android/android-ndk-r10e/sources/cxx-stl/stlport/Android.mk
  Android NDK:     Found in /Users/algingihy/Library/Android/android-ndk-r10e/sources/cxx-stl/stlport
  Android NDK: Using prebuilt STLport libraries
  Android NDK: Looking for imported module with tag 'android/cpufeatures'
  Android NDK:   Probing /Users/algingihy/Library/Android/android-ndk-r10e/sources/android/cpufeatures/Android.mk
  Android NDK:     Found in /Users/algingihy/Library/Android/android-ndk-r10e/sources/android/cpufeatures
  Android NDK: Module 'system' has C++ sources
  Android NDK: Add dependency 'stlport_static' to module 'system'
  Android NDK: [armeabi-v7a] Modules to build: pdnsd system tun2socks
  make[1]: Entering directory `/Users/algingihy/xSocks-android/jni'
  [x86] Install        : pdnsd => libs/x86/pdnsd
  [x86] Install        : libsystem.so => libs/x86/libsystem.so
  [x86] Install        : tun2socks => libs/x86/tun2socks
  [armeabi-v7a] Install        : pdnsd => libs/armeabi-v7a/pdnsd
  [armeabi-v7a] Install        : libsystem.so => libs/armeabi-v7a/libsystem.so
  [armeabi-v7a] Install        : tun2socks => libs/armeabi-v7a/tun2socks
  make[1]: Leaving directory`/Users/algingihy/xSocks-android/jni'
  ~/xSocks-android
  install: jni/xSocks/xSocks-android-i686/xSocks: No such file or directory
  install: jni/xSocks/xSocks-android-i686/xForwarder: No such file or directory
  install: jni/xSocks/xSocks-android-armv7-a/xSocks: No such file or directory
  install: jni/xSocks/xSocks-android-armv7-a/xForwarder: No such file or directory
  make: **\* [app/src/main/jniLibs/armeabi/libsystem.so] Error 71

**Comment by lparam** [comment]
Try clean 3rd lib before you build native xSocks like below:
cd jni/xSocks/xSocks-android-i686/3rd/libuv && make distclean

**Comment by aalgingi** [comment]
i was able to build after cleaning 3rd lib. Thanks!
